[package]
name = "action-chess"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.0.4"
threadpool = "1.8.1"

[workspace]

members = [
    "src/state",
    "src/network",
    "src/bin/server"
]

[[bin]]
name = "server"
test = false
bench = false
