[package]
name = "action-chess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.4"
comfy = "0.2.0"
hecs = { version = "0.10.3", features = ["macros"] }
threadpool = "1.8.1"
