[package]
name = "server"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
state = { path = "../state" }
network = { path = "../network" }
anyhow = {workspace = true}

[lints]
workspace = true

[[bin]]
name = "server"
path = "main.rs"
